### ISSUE TITLE
Arrays don't get serialized

### ISSUE THREAD

**Issue by MaDKaTZe** [LuckboxGG/logger-factory#11]
When I pass a message which has an argument of type array with the following value 
```javascript
[
  {
    "id": 4858581,
    "diff": {
      "status": {
        "oldValue": "removed",
        "newValue": "resolved"
      }
    }
  }
]
```
I'm expecting it's contents to be JSON-serialized. Here is what appears instead as message:
```javascript
[ { id: 4858581, diff: { odds: [Object] } } ]
```

**Comment by nikksan** [comment]
Fixed in https://github.com/LuckboxGG/logger-factory/pull/12
